### ISSUE TITLE
Hyprland call?

### ISSUE THREAD

**Issue by jellium** [dedSyn4ps3/nixos_desktop_configs#1]
Hello,
Thanks for sharing your configurations. I am quite new to NixOS and Home Manager. I liked your code as it is well structured (core/modules directories, etc.)
However, I don't understand where hyprland is actually called? I can see waybar but no hyprland package. Can you please explain this to me? It seems to me that you removed it from the previous commit.
Thank you.

**Comment by dedSyn4ps3** [comment]
### Hey there @jellium!

My apologies for the uber late response!!! I got caught up traveling for work and relocating and completely forgot about your issue post.

I've actually been slowly working on updating this repo to a new **Version 2** of sorts, as my configs have continue to blossom and expand these past couple months to include additional device setups as well...so stay tuned for that! :)

Regarding your initial issue: I originally had the declaration for the `Hyprland` implementation inside the Home-Manager block of `flake.nix`. It all worked just fine, but then NixOS decided to become even more awesome by directly including the hyprland WM as an option inside `configuration.nix`.

I'm not sure if by now you've become aware of this or not, but enabling it is as easy as adding the `programs.hyprland.enable = true;` to your main config!

**I wanted to make sure I still responded to ya, even if it has been...a little while... ;)**
